server:
  port: 8080

spring:
  application:
    name: seckill-system-backend

  # MySQL 配置
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  # 开启缓存支持
  cache:
    type: redis

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seckill.backend.entity

# 日志
logging:
  level:
    com.seckill.backend.mapper: debug

# Actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: health,info